grid-columns: 1
services: "" {
  grid-columns: 3
  Common Services: {
    grid-rows: 5
    Client Registry
    Facility Registry
    Health Worker Registry
    Product Catalogue
    Terminology Services
  }
  Business Services: {
    grid-rows: 4
    Finance and Insurance Service
    Health Management Information System
    Logistics Management Information System
    Shared Health Record
  }
  Analytical Services: {
  }
}
Interoperability Layer.width: 800
Point-of-Care Systems.width: 800
